### ISSUE TITLE
Documentation request: i18n example 

### ISSUE THREAD

**Issue by KeithPepin-CyG** [joanllenas/ngx-date-fns#128]
**Description of the Issue and Steps to Reproduce:**
I see from other issues that your pipes support passing in an options argument for date-fns, and thus it supports i18n. I'm new to date-fns however, and haven't written many pipes of my own yet.I would really love to see an example of how i18n works with the angular pipes you provide for the library since loading the locale and passing in the desired locale may not be immediately obvious.

Did you search for duplicate issue? [Yes / No]
Yes

Please describe the issue and steps to reproduce, preferably with a code sample / plunker:
No real steps to reproduce, just looking for a clear i18n example in the README.md file of the project if it isn't too much trouble.

*Ensure your issue is isolated to ngx-date-fns. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

**Environment:**

Please answer the following questions:

* Angular version? 
4.x
* TypeScript version?
2.3.4
* `date-fns` version?
1.29.0

**Comment by joanllenas** [comment]
Hi, I have added an example with locales in the README.
I hope it clarifies how it works.
Cheers

**Comment by KeithPepin-CyG** [comment]
Excellent, thank you!
