### ISSUE TITLE
Integrate with angular's locale

### ISSUE THREAD

**Issue by victornoel** [joanllenas/ngx-date-fns#135]
Is there any plan to integrate with the localization used by angular instead of having it being passed by options manually?

This would work in the same way as the i18n pipes of angular, see https://angular.io/api/core/LOCALE_ID.

**Comment by joanllenas** [comment]
Hi, thanks for suggesting.
That would be a good addition indeed!
I'll have a look when I have some time, probably during this month.

**Comment by joanllenas** [comment]
@victornoel [ngx-date-fns v2.0.2](https://github.com/joanllenas/ngx-date-fns/releases/tag/v2.0.2) comes some additions to work with global locales.
You can find the details in the documentation: https://github.com/joanllenas/ngx-date-fns#working-with-locales

Cheers!

**Comment by victornoel** [comment]
@joanllenas thx, that's great!
