### ISSUE TITLE
Update to date-fns 2.0.0

### ISSUE THREAD

**Issue by nfdevil** [joanllenas/ngx-date-fns#178]
Update the library to use date-fns 2.0.0.
Currently, using it with date-fns 2.0.0, it gives multiple warnings of functions not being found, ex.:

```
WARNING in ./node_modules/ngx-date-fns/esm5/ngx-date-fns.es5.js 1090:15-26
"export 'addISOYears' was not found in 'date-fns'
```

**Comment by nfdevil** [comment]
I've created a PR with the changes: #179

**Comment by joanllenas** [comment]
That's great @nfdevil !
I'll have a look ASAP, likely over the weekend. (I'm on vacation right now).

**Comment by nfdevil** [comment]
Sure, enjoy :)!

**Comment by joanllenas** [comment]
Hey @nfdevil 
I have merged your pull request.

While I figure out a couple of issues and wait for the final `date-fns` version I will be releasing `ngx-date-fns@next` versions.

Thanks a lot for this great contribution.
Cheers!

**Comment by toverux** [comment]
Just wanted to say that [date-fns v2 is out](https://github.com/date-fns/date-fns/releases/tag/v2.0.0)! (finally...) :smile:
