### ISSUE TITLE
Runtime locale change & OnPush strategy

### ISSUE THREAD

**Issue by toverux** [joanllenas/ngx-date-fns#208]
Hello,

I am using `OnPush` components and `DateFnsConfigurationService.setLocale` to change language at runtime. I react to `LangChangeEvent`s from ngx-translate to sync the locale used by ngx-date-fns.

The thing is, I use OnPush components and that prevents Angular from cheking the pipes used in the component. Since the locale is changed outside of the Inputs of the component, Angular doesn't replays the pipes' transform.

However, the pipes from ngx-translate work just fine when changing the locale globally. So I went to see how they've done, and each pipe subscribes to locale changes from the `TranslateService` and mark themselves for check : https://github.com/ngx-translate/core/blob/master/projects/ngx-translate/core/src/lib/translate.pipe.ts#L25.

Would it be possible to implement the same here, on the library's side? For now I'll workaround that with the component subscribing to changes from my custom service, in order to call the change detector from the component.

Little addendum: the declaration of `locale()` / `setLocale()` could be improved so they take/return `object | undefined` instead of `Object`. `undefined` is the built-in "en" locale. In `strictNullChecks` mode, it causes type-checking error and I have to cast the value.

Thanks for your work!

PS: On a side note, will you plan to support date-fns v.2 when it's out ?

**Comment by joanllenas** [comment]
Hi @toverux , I'll take a look at both the `DateFnsConfigurationService.setLocale` + `OnPush` and the `strictNullChecks` issues during this week.

Regarding date-fns v2 there's already a WIP on master thanks to a PR made by [@nfdevil](https://github.com/nfdevil) and published to npm as `ngx-date-fns@next`. I will finish the work once v2 final is released.

Cheers!

**Comment by joanllenas** [comment]
Hi @toverux ,
I just released v2.0.3 with your suggestions.

The version number is not correct though, because there's actually a breaking change. If you implemented your own `DateFnsConfiguration` you have to add the `Subject` that pipes will subscribe to in order to get notified by locale changes.
The default implementation: https://github.com/joanllenas/ngx-date-fns/blob/v2/src/lib/src/date-fns-configuration.service.ts#L24

Hopefully, this doesn't hurt too many people 😐

Cheers!

**Comment by toverux** [comment]
Cool!
I'll upgrade later but I'm pretty sure this will be alright :)
Thanks a lot!
