### ISSUE TITLE
Allow to import pipe selectively

### ISSUE THREAD

**Issue by unsafecode** [joanllenas/ngx-date-fns#215]
**Description of the Issue and Steps to Reproduce:**

Looks like the current implementation always imports all the pipe, making the final bundle excessively large:

![image](https://user-images.githubusercontent.com/1794924/49367855-868efd00-f6ed-11e8-9258-b2a1dca6273f.png)

It would be better to be able to import pipes in a more selective way, in order not to increase the final app size including unused code.

**Environment:**

Please answer the following questions:

* Angular version? **7.1.0**
* TypeScript version? **3.1.6**
* `ng-xdate-fns` version? **2.0.3**

**Comment by gmanoj26** [comment]
@joanllenas : As date-fns v2 is released. do we have any update on this open issue.

**Comment by joanllenas** [comment]
Hi @gmanoj26 ,
I took a look a while ago and didn't find a solution to the problem. V2 by itself didn't solve the issue.
Maybe, for this to work we need something like what [this article](https://indepth.dev/angular-revisited-tree-shakable-components-and-optional-ngmodules/) suggests; one pipe per module; but I think it's not a good idea given the number of pipes this library contains.

I'm open to discussing possible solutions if someone has the time to investigate.

**Comment by joanllenas** [comment]
I added a section about tree shaking in the docs.
I hope this helps: https://github.com/joanllenas/ngx-date-fns#tree-shaking-date-fns

**Comment by KingDarBoja** [comment]
In order to make each pipe tree-shakable, those must be provided as secondary entry points (as stated by the article, 1 pipe per entry point / module). It can be easily done using [ng-samurai](https://github.com/kreuzerk/ng-samurai) schematics.

Willing to look into this as I am using this library but not being tree-shakable atm.
