### ISSUE TITLE
rxjs-compat need

### ISSUE THREAD

**Issue by beradrian** [joanllenas/ngx-date-fns#216]
I think rxjs-compat is needed. You could replace imports like import { Subject } from "rxjs/Subject" with import { Subject } from "rxjs'

**Comment by joanllenas** [comment]
Hi @beradrian ,
the current stable version uses rxjs v5.5, the one on master is already migrated to rxjs v6 and all imports follow that pattern.

The version on master depends on date-fns v2, which is on alpha.25 right now, so when it is released I will finish the migration and release as well.

Thanks for reporting,
cheers!
