### ISSUE TITLE
Error is is not a Module when adding locales

### ISSUE THREAD

**Issue by JesusCN** [joanllenas/ngx-date-fns#257]
Hi, 

I followed the instructions to **Changing locale globally.**

The next error appears: 

ERROR in src/app/app.module.ts(43,27): error TS2306: File '.../node_modules/date-fns/locale/es/index.d.ts' is not a module.

I can serve the app and is working but the error is very anoying. 

What can i do ?¿ 

* Angular version? 7.2.12
* TypeScript version? 3.2.4
* `date-fns` version? 1.30.1

Thanks in advance.

**Comment by joanllenas** [comment]
Hi @JesusCN ,
I'll take a look ASAP.

Meanwhile, you can try downgrading date-fns to v1.29. That's the version this library has been developed/tested with and shouldn't be problematic. I'm not sure what changed from 1.29 to 1.30 but there are no API changes. It should be safe.

Cheers

**Comment by JesusCN** [comment]
Hi @joanllenas,

Thanks for the quick reply !! I can confirm you that the error didnt show up with v1.29 of date-fns. 

Thanks again. 

Cheers
