### ISSUE TITLE
Missing DateFnsConfigurationService in pipes

### ISSUE THREAD

**Issue by JoeFamiliar** [joanllenas/ngx-date-fns#309]
Hi Joan!

Thanks for the great library.

Why you don't use `DateFnsConfigurationService` and `calculateLocale()` in most of pipes, e.g.  [start-of-week](https://github.com/joanllenas/ngx-date-fns/blob/master/projects/ngx-date-fns/src/lib/start-of-week.pipe.ts ) as you used it in [format-distance](https://github.com/joanllenas/ngx-date-fns/blob/master/projects/ngx-date-fns/src/lib/format-distance.pipe.ts) for getting default locale options?

Do you plan to upgrade your pipes or can we propose you to make merge requests?

**Comment by breslavsky** [comment]
I have the same problem. It will be very useful.

**Comment by joanllenas** [comment]
Hi! I missed that one.

Most pipes don't need locale support, that's why I keep them locale agnostic. Adding locale support also means turning pipes impure, which should be done only when strictly necessary, given that they are called for every change detection cycle.

Thanks for reporting, I'll take a look ASAP.

**Comment by breslavsky** [comment]
@JoeFamiliar thanks for the answer.

When you are saying about "impure pipes", do you mean switching locale in runtime?

In our project, we are using [angular i18n](https://angular.io/guide/i18n). It means that our app fully built on target locale. There are no runtime locale changes. Each language has own dist. Probably it is possible to configure your library like:

```typescript
import ru from 'date-fns/locale';
@NgModule({
  imports: [
    DateFnsModule.forRoot({locale: ru})
  ]
```
In this case, we will not be able to change locale in runtime and pipes could be pure.

Sure, it will be very useful to be sure that all date functions working using one locale without thinking about it each time.

Thanks a lot for your job!

**Comment by joanllenas** [comment]
@breslavsky you can already configure the library like that. Check this out: https://github.com/joanllenas/ngx-date-fns#changing-locale-globally

**Comment by breslavsky** [comment]
Yes, but in this case, I have access to 

`constructor(public config: DateFnsConfigurationService) {}`

in my components and I can change locale in runtime and you should we be worried about updating pipes.

Using this approach

```
import ru from 'date-fns/locale';
@NgModule({
  imports: [
    DateFnsModule.forRoot({locale: ru})
  ]
```

Locale will be set once while the module initialized. `DateFnsConfigurationService` will private in your module and will not be exported.

**Comment by joanllenas** [comment]
Sorry, I think I'm not following. I still think that what you are suggesting is already possible.
Do you mind opening a new issue with the improvement suggestion, please? we can discuss it there (so we keep one issue per topic).

**Comment by joanllenas** [comment]
@JoeFamiliar [v6.0.0](https://github.com/joanllenas/ngx-date-fns/releases/tag/v6.0.0) is ready with the fixes.
Cheers!

**Comment by JoeFamiliar** [comment]
@joanllenas  awesome! Great job! Thx a lot))
