### ISSUE TITLE
Configure locale in module

### ISSUE THREAD

**Issue by breslavsky** [joanllenas/ngx-date-fns#313]
Hi @joanllenas as we discussed in https://github.com/joanllenas/ngx-date-fns/issues/309

I offer to configure locale in module directly `DateFnsModule.forRoot({locale: ru})`.

The main advantage of this is all pipes could be pure and that will be good for performance.

```javascript
import ru from 'date-fns/locale';
@NgModule({
  imports: [
    DateFnsModule.forRoot({locale: ru})
  ]
```

The disadvantage is that we will not be able to change locale dynamically. 

Or we will need to reload the page, e.g.
```javascript
import ru, de from 'date-fns/locale';

let locale;
const code = localStorage.locale || 'ru';
switch(code) {
  case 'de':
    locale = de;
  break;
  default:
     locale = ru;   
}

@NgModule({
  imports: [
    DateFnsModule.forRoot({locale: locale})
  ]
```

What do you think? Thanks a lot!

**Comment by joanllenas** [comment]
Hi @breslavsky ,
I understand your concern.

Instead of removing the feature of changing locales at runtime my plan is to create pure versions of all impure pipes ( check this out: https://github.com/joanllenas/ngx-date-fns/issues/160 ) and you'll still be able to use

```
const frenchConfig = new DateFnsConfigurationService();
frenchConfig.setLocale(fr);

@NgModule({
  imports: [
    // (...)
    DateFnsModule.forRoot()
  ],
  providers: [
    // (...)
    { provide: DateFnsConfigurationService, useValue: frenchConfig } // <-- All pipies in French by default
  ]
})
```

Subscribe to #160 to keep track of progress.
Cheers!

**Comment by breslavsky** [comment]
I think it is possible to save `DateFnsConfigurationService` as public API.

But we can add the possibility for 

```javascript
import ru from 'date-fns/locale';
@NgModule({
  imports: [
    DateFnsModule.forRoot({locale: ru})
  ]
```

For me it is beauty :-)

**Comment by joanllenas** [comment]
#160 has been closed via https://github.com/joanllenas/ngx-date-fns/releases/tag/v6.4.0
