### ISSUE TITLE
Pipes isFuture, isPast, isToday

### ISSUE THREAD

**Issue by JoeFamiliar** [joanllenas/ngx-date-fns#316]
Hello again)
Do you plan to add pipes based on date-fns functions like isToday, isPast and isFuture?

**Comment by joanllenas** [comment]
Hi Joe,
Sure, I can add them 👍

**Comment by breslavsky** [comment]
I need these pipes too :-)

**Comment by joanllenas** [comment]
This is available on v6.1.0.
See: https://github.com/joanllenas/ngx-date-fns/releases/tag/v6.1.0
Closing
