### ISSUE TITLE
Pipes isToday, isWeekend, isSameMonth

### ISSUE THREAD

**Issue by JoeFamiliar** [joanllenas/ngx-date-fns#328]
Hi Joanllenas!
Thx for adding pipes in [this issue](https://github.com/joanllenas/ngx-date-fns/issues/316)! But you didn't add isToday, it will be nice to use it
And also will be good to have pipes such as isWeekend and isSameMonth or something like this
Thx a lot for you job!)

**Comment by JoeFamiliar** [comment]
And do you plan to add dfnsParse pipe?

**Comment by joanllenas** [comment]
Hi @JoeFamiliar,
Now I see I missed that one...

I can add all of them:
- isToday
- isWeekend
- isSameMonth
- parse

Cheers!

**Comment by JoeFamiliar** [comment]
> Hi @JoeFamiliar,
> Now I see I missed that one...
> 
> I can add all of them:
> 
> * isToday
> * isWeekend
> * isSameMonth
> * parse
> 
> Cheers!

Awesome news!) waiting for this)) Cheers!

**Comment by joanllenas** [comment]
This is ready in version [v6.2.1](https://github.com/joanllenas/ngx-date-fns/releases/tag/v6.2.1)
Closing
