### ISSUE TITLE
IsSameYear pipe

### ISSUE THREAD

**Issue by JoeFamiliar** [joanllenas/ngx-date-fns#329]
Hello, @joanllenas 
Thx for your last [update](https://github.com/joanllenas/ngx-date-fns/issues/328)
You have added IsSameMonth, IsSameYear will be nice to use too)
Thx a lot!

**Comment by joanllenas** [comment]
Hi @JoeFamiliar ,
Sure, I'll take a look ASAP.

**Comment by joanllenas** [comment]
Hi @JoeFamiliar ,
v6.3.0 includes the `IsSameYearPipe` pipe. 
- https://github.com/joanllenas/ngx-date-fns/releases/tag/v6.3.0

Cheers!

**Comment by JoeFamiliar** [comment]
@joanllenas thx a lot! cheers)
