### ISSUE TITLE
Support `strictTemplates` / All pipes should accept null and undefined

### ISSUE THREAD

**Issue by MickL** [joanllenas/ngx-date-fns#347]
With Angular [strict mode](https://angular.io/guide/strict-mode) all inputs need to be optional:

```ts
export class myComponent implements OnInit {
  @Input() myDate?: number;
}
```

Or using the async pipe returns `null`:

```ts
<app-my-compontent [myDate]="myDate$ | async"></app-my-component>
```

But then the compiler is throwing an error with ngx-date-fns pipes, e.g.:

>  Type 'undefined' is not assignable to type 'DateFnsInputDate'.
>  {{ myDate | dfnsFormat: 'dd.MM.yyyy'}}

I would suggest to add strict typechecking to tsconfig:

```
"angularCompilerOptions": {
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true,
    "preserveSymlinks": true
  }
```

 and add a questionmark to all pipe inputs to support `undefined` and also accept `null`, e.g. the format pipe:

```ts
transform(
    date?: DateFnsInputDate | null,
    ...
  ): string {
    if (!date || isInvalidDate(date)) {
      return '';
    }
    ...
  }
}
```

**Comment by joanllenas** [comment]
Hi @MickL ,
I'll take a look at this during the weekend.
Thanks!

**Comment by MickL** [comment]
I added "null" to the example because when using the async pipe it can return null and undefined is not null: `{{ (myDate$ | async) | dfnsFormat: 'dd.MM.yyyy'}}`

**Comment by joanllenas** [comment]
@MickL [v7.0.2](https://github.com/joanllenas/ngx-date-fns/releases/tag/v7.0.2) implements this change.

Note that this has only been implemented for pipes that return a string representation of a date. The rest of the pipes that make calculations with dates are not affected because the input has to be valid.

**Comment by MickL** [comment]
Awesome :)
