### ISSUE TITLE
Deprecated package?

### ISSUE THREAD

**Issue by hwebb** [joanllenas/ngx-date-fns#349]
Just FYI, your package doesn't work anymore.
I get nearly 100 errors like "node_modules\ngx-date-fns\fesm2015\ngx-date-fns.js depends on 'date-fns/parseISO'. CommonJS or AMD dependencies can cause optimization bailouts.". I thought it was coming from date-fns, but after a lot of headache I decided to remove your package, and by my surprise date-fns was working just fine without it!
I'm wondering what is ngx-date-fns doing?

**Comment by joanllenas** [comment]
Hi @hwebb ,

> your package doesn't work anymore.

You mean that you had an application where the lib was working, then you upgraded to a newer version and it stopped working? if that is the case, can you tell me which versions?

> I get nearly 100 errors like "node_modules\ngx-date-fns\fesm2015\ngx-date-fns.js depends on 'date-fns/parseISO'. CommonJS or AMD dependencies can cause optimization bailouts.".

Ok, those 100 errors you mention are actually warnings. Each warning comes with a link, If you click on it you'll find instructions about how to avoid them.

> I'm wondering what is ngx-date-fns doing?

What do you mean?

**Comment by jpduckwo** [comment]
Hi, I'm also having this issue after upgrading ngx-date-fns 7.0.0 > 7.0.2. I think the concern part is why it's picking it up as a commonjs import now where as before it wasn't and it shouldn't be I think.

**Comment by jpduckwo** [comment]
I believe there is something wrong with the format of the date-fns package version 2.17.0. Try to install 2.16.1 and test again
`npm install date-fns@2.16.1`
This fixed all my issues...

**Comment by joanllenas** [comment]
Feel free to reopen if you still need help.

**Comment by MickL** [comment]
I guess the warnings @hwebb described are not related to his problem. ngx-date-fns working fine for me, I am on date-fns 2.16.1.

**Comment by joanllenas** [comment]
Hi @hwebb you need to install  date-fns `v2.16.1` or `>= v2.21.1`
I updated the installation instructions here: https://github.com/joanllenas/ngx-date-fns#installation
It's very confusing, I hope this helps.

**Comment by hwebb** [comment]
I just updated date-fns to 2.21.1 and it worked indeed! I should have started with that.
