### ISSUE TITLE
IsEqual Pipe

### ISSUE THREAD

**Issue by macure** [joanllenas/ngx-date-fns#352]
**Description of the Issue and Steps to Reproduce:**

Did you search for duplicate issue? [Yes / No] Yes

Please describe the issue and steps to reproduce, preferably with a code sample / plunker:

Hi it looks like dfnsIsEqual pipe is not working properly. Or maybe I'm doing something wrong.
Here you can find dfnsIsEqual (results: false) together with isEqual function (results: true)
https://stackblitz.com/edit/ngx-date-fns-is-equal?file=src/app/hello.component.ts

*Ensure your issue is isolated to ngx-date-fns. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

**Environment:**

Please answer the following questions:

* Angular version? 11.2.3
* TypeScript version? Stackblitz
* `date-fns` version? 7.0.2

**Comment by joanllenas** [comment]
Hi @macure ,
the correct syntax would be: 
```
<h2>Is date the same [PIPE]: {{ dateOne | dfnsIsEqual : dateTwo }}!</h2>
                                                      ^--- a        ^--- b           ^--- c
```

- a: 1st dfnsIsEqual param
- b: the pipe
- c: 2nd dfnsIsEqual param

Cheers!

**Comment by macure** [comment]
@joanllenas Awesome! Thanks a lot!
