### ISSUE TITLE
Documentation about tree shaking is not correct

### ISSUE THREAD

**Issue by MickL** [joanllenas/ngx-date-fns#355]
The documentation says: 

> The library itself is optimized to be tree-shakable by just importing DateFnsModule.forRoot()

I did this and checked with `ng build --stats-json` and then using `webpack-bundle-analyzer` to see full 512kb ngx-date-fns is imported:

<img width="1047" alt="Bildschirmfoto 2021-03-09 um 12 59 55" src="https://user-images.githubusercontent.com/5103210/110467482-5f4ae580-80d7-11eb-9f07-81c2df3709d6.png">

But when I import just the specific pipe it works and ngx-date-fns is not even visible.

Dont try to reproduce with something newer than 2.16.1 since newer versions do not support tree shaking in the first place: https://github.com/date-fns/date-fns/issues/2207

**Comment by joanllenas** [comment]
@MickL I tested the bundle size with `webpack-bundle-analyzer` as you suggested but I think it's not working properly.
The command used to test tree shaking in this project is `npm run analyze:app` which uses `source-map-explorer`, and if you double-check with the actual `main.js` size, it makes sense.

# date-fns v2.19.0

![Screenshot 2021-03-14 at 13 17 12](https://user-images.githubusercontent.com/213787/111069767-e250af00-84ce-11eb-81fc-60bb9e98d3ee.png)
![Screenshot 2021-03-14 at 14 01 34](https://user-images.githubusercontent.com/213787/111069772-e8df2680-84ce-11eb-9328-af0359c249c6.png)


# date-fns v2.16.1
![Screenshot 2021-03-14 at 14 10 19](https://user-images.githubusercontent.com/213787/111069804-10ce8a00-84cf-11eb-9084-811305588591.png)
![Screenshot 2021-03-14 at 13 56 39](https://user-images.githubusercontent.com/213787/111069815-1a57f200-84cf-11eb-98f8-87f29dbb90c2.png)

# Issues with webpack-bundle-analyzer
I don't know the exact details about why the tool is not working properly, but I found a couple of places where they recommend aginst using it for Angular:

([source](https://coryrylan.com/blog/measuring-angular-performance-with-source-map-explorer))
> While the Angular CLI uses Webpack for some of its bundling, it also makes additional optimizations on top of Webpack. Because of these optimizations, it's important to use the source-map-explorer to test the final output and not the webpack-bundle-analyzer that is commonly used with Webpack based applications.

([source](https://stackoverflow.com/a/46575670))
> The angular team strongly recommends to only use source-map-explorer to analyze your bundle size instead of webpack-bundle-analyzer. According to them, webpack-bundle-analyzer and a few other similar tools doesn't give the actual info pertaining to angular build process.


Thanks for taking the time to explore this issue and for the `v2.16.1` issue finding. I will add a note to the readme.
Cheers!
