### ISSUE TITLE
FR: dfnsFormatRelativeToNow

### ISSUE THREAD

**Issue by joeveiga** [joanllenas/ngx-date-fns#363]
**Description of the Issue and Steps to Reproduce:**

Hello 👋 ! I'd like to propose the addition of a new `dfnsFormatRelativeToNow` pipe which assumes `new Date()` as the second argument. Alternatively you could modify `dfnsFormatRelative` pipe to behave that way [here](https://github.com/joanllenas/ngx-date-fns/blob/9cd7d2430e32fb9eef5881a7c79586ba6cc712f2/projects/ngx-date-fns/src/lib/format-relative.pipe.ts#L37), but I understand perhaps you want to keep that pipe consistent with the original behavior in `date-fns` (although having a default wouldn't be a breaking change, IMO).

**Motivation**

For my usecase(s), and probably others as well, the most common scenario in which I use that pipe is I want to see the date relative to "now". The required pipe argument becomes an issue because then in every component I need to have a field to expose the current date, like so:

```typescript
@Component({
  template: '<div>{{ someDate | dfnsFormatRelative: now }}</div>'
})
export class MyComponent {
  get now(): Date {
    return new Date();
  }
  // ...
}
```
I'd much rather not have to create my own pipe just to add that default argument 😄 .
Thanks!

**Comment by joanllenas** [comment]
Hi @joeveiga ,
I like the idea of `dfnsFormatRelativeToNow, and I'm pretty sure other users will benefit from this.
I will be releasing a new version with the new pipe in the coming days.
Cheers!

**Comment by joeveiga** [comment]
@joanllenas Thank you! 🙏

**Comment by joanllenas** [comment]
@joeveiga this is ready!
https://github.com/joanllenas/ngx-date-fns/releases/tag/v8.2.0
Cheers!

**Comment by joanllenas** [comment]
Closing
