### ISSUE TITLE
Angular 13 : "Encourage the library authors to publish an Ivy distribution"

### ISSUE THREAD

**Issue by marcwrobel** [joanllenas/ngx-date-fns#369]
During the build of a project, angular-cli 13 issues the following message :
```
⠙ Generating browser application bundles (phase: setup)...Processing legacy "View Engine" libraries:
- ngx-date-fns [es2015/esm2015] (git+https://github.com/joanllenas/ngx-date-fns.git)
Encourage the library authors to publish an Ivy distribution.
```

Except this message ngx-date-fns works fine. But it seems something has to be done in the ngx-date-fns library.

**Comment by joanllenas** [comment]
Hey @marcwrobel ,
Nice catch 👍  I will take a look when I have some time.
Thank for reporting!

**Comment by MorganWaya** [comment]
Hi everyone. I don't know if it is related but I obtain the following message with Angular 13:

`core.mjs:1122 Uncaught Error: Type DateFnsModule does not have 'ɵmod' property.
`

With

```
    "@angular/core": "~13.1.0",
    "date-fns": "^2.28.0",
    "ngx-date-fns": "^8.3.0",
```

Any idea? Thank you for your work <3

**Comment by marcwrobel** [comment]
Hi @MorganWaya, I did not see this message after upgrading to ngx-datefns 8.3.0 / date-fns 2.28.0 / angular 13.1.1. Did you found more information about it since you posted your comment ?

**Comment by MorganWaya** [comment]
Hi!

It looks ok with the latest version, thank you!

**Comment by jpduckwo** [comment]
Keen to see this release, thanks for your efforts @joanllenas

**Comment by joanllenas** [comment]
Hey, I have a [PR](https://github.com/joanllenas/ngx-date-fns/pull/378) ready.
Follow the instructions on the PR comment to try the beta and let me know if it works, or there are any issues.
Thanks!

**Comment by joanllenas** [comment]
Closed via https://github.com/joanllenas/ngx-date-fns/releases/tag/v9.0.0
