### ISSUE TITLE
Angular 16 support

### ISSUE THREAD

**Issue by mohamed-badaoui** [joanllenas/ngx-date-fns#399]
Angular 16 support ?

Please answer the following questions:

Angular version? 16.x
TypeScript version? 5.x

**Comment by mohamed-badaoui** [comment]
Sorry, I thought it was compatible only until angular 15.x.
I were wrong, it works fine with angular 16.x  
Thanks.

**Comment by isaac-manubag** [comment]
@joanllenas how can I import the pipes properly on Angular v16?
sample code

```
<span>{{ note?.author?.full_name}} - {{ note.created_at | dfnsParseIso | dfnsFormat:'dd MMM yyyy'}}</span>
```

```
@Component({
  selector: 'customer-general-tab',
  standalone: true,
  templateUrl: './customer-general-tab.component.html',
  styleUrls: ['./customer-general-tab.component.scss'],
  imports: [
    CommonModule,
    ParseIsoPipeModule,
    FormatPipeModule,
  ],
})
```

Error: 
![image](https://github.com/joanllenas/ngx-date-fns/assets/8652190/498bd118-8fed-4b7f-aa4f-e87d762157c5)

**Comment by joanllenas** [comment]
Hi @isaac-manubag 
Here's an example: https://stackblitz.com/edit/stackblitz-starters-kt3tcp?file=src%2Fmain.ts
Hope it helps
