### ISSUE TITLE
date-fns 3.x support

### ISSUE THREAD

**Issue by sergey-morenets** [joanllenas/ngx-date-fns#401]
**Description of the Issue and Steps to Reproduce:**

Hi

I tried to upgrade my project dependencies and switched from date-fns 2.30.0 to 3.0.6.
However I received a lot of errors after that:

`  Type 'typeof import("/node_modules/date-fns/closestTo")' provides no match for the signature '(...args: any): any'. [plugin angular-compiler]`

 ```
[ERROR] TS2304: Cannot find name 'Duration'. [plugin angular-compiler]

    node_modules/ngx-date-fns/lib/format-duration.pipe.d.ts:11:24:
      11 │     transform(duration: Duration, options?: {
```

```
 [ERROR] TS2304: Cannot find name 'Locale'. [plugin angular-compiler]

    node_modules/ngx-date-fns/lib/is-match.pipe.d.ts:12:17:
      12 │         locale?: Locale;
```

**Environment:**

Please answer the following questions:

* Angular version? 17.0.8
* TypeScript version? 5.2.2
* `date-fns` version? 3.0.6

**Comment by joanllenas** [comment]
Hi @sergey-morenets ,
I've also noticed the new version. I'll review the requirements for migrating to version 3. I'll keep you posted.
Thanks for reporting

**Comment by sergey-morenets** [comment]
> Hi @sergey-morenets , I've also noticed the new version. I'll review the requirements for migrating to version 3. I'll keep you posted. Thanks for reporting

Hi @joanllenas 

Thank you for the quick response. Will wait for the fixes.

**Comment by sergey-morenets** [comment]
List of all breaking changes:
https://github.com/date-fns/date-fns/releases/tag/v3.0.0

**Comment by joanllenas** [comment]
@sergey-morenets you can start using date-fns v3 🎉 

https://github.com/joanllenas/ngx-date-fns/releases/tag/v11.0.0

**Comment by sergey-morenets** [comment]
> @sergey-morenets you can start using date-fns v3 🎉
> 
> https://github.com/joanllenas/ngx-date-fns/releases/tag/v11.0.0

Thank you a lot, @joanllenas
